package com.nus.tt02backend.models.enums;

public enum BookingStatusEnum {
    UPCOMING, ONGOING, COMPLETED, CANCELLED, PENDING_VENDOR_DELIVERY, PENDING_VENDOR_PICKUP,  PREPARE_FOR_SHIPMENT, PREPARE_FOR_PICKUP, SHIPPED_OUT, READY_FOR_PICKUP, DELIVERED, PICKED_UP,

}
