package com.nus.tt02backend.models.enums;

public enum DealCategoryEnum {
    CHINESE_NEW_YEAR,NATIONAL_DAY,DEEPAVALLI, VALENTINES, NEW_YEAR_DAY, HARI_RAYA,
    NUS_WELLBEING_DAY, SINGLES_DAY, BLACK_FRIDAY, CHRISTMAS, GOVERNMENT
}
