package com.nus.tt02backend.models.enums;

public enum SupportTicketCategoryEnum {
    REFUND, CANCELLATION, GENERAL_ENQUIRY, BOOKING, MASTER_ACCOUNT_CREATION, WALLET,
    DEAL, RESTAURANT, ATTRACTION, TELECOM, ACCOMMODATION
}
